feature/new_kiosk_nodes_33
CS3733TeamBeta/Faulkner.Kiosk pull request #79
Opened 2017-02-26 21:27 UTC by sjpridotkas

Adding kiosk class and fuctionality

2017-02-26 21:36 UTC, bhylak commented
Build failed..

2017-02-26 22:10 UTC, benhylak requested changes
Just address a few simple changes, particularly the visibility of the kiosks list

2017-02-26 22:10 UTC, bhylak commented on src/Boundary/AdminMapBoundary.java
> +                n = newKiosk;
Glad you figured out why its setup like this. (has to do with how a lambda can reference things)

2017-02-26 22:10 UTC, bhylak commented on src/Boundary/AdminMapBoundary.java
> +        } else {
Is it possible to make kiosks protected and instead have a "getKiosks()" function or "containsKiosk" function

2017-02-26 22:10 UTC, bhylak commented on src/Boundary/AdminMapBoundary.java
> +    }
Same thing here.. "setCurrentKiosk" function

2017-02-26 22:10 UTC, bhylak commented on src/Controller/Map/Admin/PopUp/KioskEditController.java
> +    }
Does this have  drop down for direction its facing? (N, S, E, W, etc.)

2017-02-26 22:10 UTC, bhylak commented on src/Entity/Hospital.java
> +    public static Kiosk currentKiosk = null;
should be private and not static

2017-02-26 22:10 UTC, bhylak commented on src/Entity/Hospital.java
> +    public static ObservableList<Kiosk> kiosks;
should be just "protected"

2017-02-26 22:10 UTC, bhylak commented on src/Entity/Hospital.java
> +        kiosks.add(newKiosk);
Okay so you already have this!  Just change visibility of the variable and then switch over the boundary code to use these functions

2017-02-26 22:10 UTC, bhylak commented on src/Entity/Map/Kiosk.java
> +
Looks good

2017-02-27 00:36 UTC, benhylak approved these changes

2017-02-27 08:04 UTC, merged

2017-03-02 22:37 UTC, iancj97 commented
This branch can be deleted